TNG/momo-scheduler

- README.md
- momo_logo.svg
Signed-off-by: Jan Eisenmenger <jan.eisenmenger@tngtech.com>
> added new logo and insert into readme.

- .github/workflows/ci.yml
- test/integration/schedule.spec.ts
> Build, test and lint on every push and pull request

- package.json
- release.sh
> Add release script for automatic tagging and npm publishing

- src/job/MomoJobBuilder.ts
- src/schedule/MongoScheduleBuilder.ts
- test/job/MomoJobBuilder.spec.ts
- test/schedule/MongoScheduleBuilder.spec.ts
Implement builder pattern for MomoJob and MongoSchedule.
> Momo 9 builder pattern fur job

- src/scheduler/JobScheduler.ts
> Fix log message to print correct scheduled execution time

- README.md
> fix: mention new error type 'stopping job failed' in README.md

- momo_logo.svg
New logo version with pointer petals :tm:
> Update logo version

- README.md
so that it looks better on npm
> docs: improve syntax highlighting in readme

- package.json
so that people will be able to find it more easily
> docs: added keywords to package

- package-lock.json
- package.json
> chore: update version to 0.3.0

- .github/workflows/update_notice.yml
> fix: simplify ort command (also makes it faster)

- CHANGELOG.md
- THIRD_PARTY_NOTICE
- package-lock.json
- package.json
Signed-off-by: weissu42 <weissu42@users.noreply.github.com>
> chore: update version to 0.4.1

- src/repository/Repository.ts
Signed-off-by: Yani Kolev <yani.kolev@tngtech.com>
> fix: use correct type for the filter

- test/schedule/momo.integration.spec.ts
> test: increase waiting time for "immediate" things from 100 to 200 ms

- README.md
- test/job/Job.spec.ts
> Fix readme job examples

- .eslintrc.js
- src/logging/LogEmitter.ts
- test/schedule/Schedule.spec.ts
- test/scheduler/JobScheduler.spec.ts
> chore: enforce empty lines between import groups with eslint

- CHANGELOG.md
- THIRD_PARTY_NOTICE
- package-lock.json
- package.json
Signed-off-by: NiklasEi <NiklasEi@users.noreply.github.com>
> chore: update version to 1.1.1

- package-lock.json
> fix: fix CVE-2023-34104 for fast-xml-parser

- prepare_release.sh
- release.sh
> chore: move the release tag to the commit that actually gets published

- CHANGELOG.md
- THIRD_PARTY_NOTICE
- package-lock.json
- package.json
Release version 2.0.2 with dependency updates and bugfixes
> V2.0.2 release

- renovate.json
> chore: preserve semVer ranges for renovateBot

- src/executor/JobExecutor.ts
- test/executor/JobExecutor.spec.ts
- test/utils/logging.ts
> feat: handle improper error objects in job executor

- renovate.json
> chore: fix renovate config for dev-dependencies

- package-lock.json
- package.json
cron and pino provide their own types, so we no longer need the separate types for them
> chore: remove unnecessary stub types

- package.json
> chore: adjust repository url in package.json with "npm pkg fix"
